run: compile
	./main1
	./main2
	./main3
	
compile:
	gcc -Wall exercice1.c -lm -g -o main1
	gcc -Wall exercice2.c -lm -g -o main2
	gcc -Wall exercice3.c -lm -g -o main3
	
clean:
	rm main1
	rm main2
	rm main3

