run: compile
	./main
	./main2
	./main3
	
compile:
	gcc -Wall exercice1.c -lm -g -o main
	gcc -Wall exercice2.c -lm -g -o main2
	gcc -Wall exercice3.c -lm -g -o main3
	
clean:
	rm main
	rm main2
	rm main3
